// Public surface of the budget engine (D2 + D3). The app imports from here only.
export { createBudgetEngine, type EngineDeps } from "./engine";
export { EngineError, type EngineErrorCode } from "./errors";
export {
  assessFundPace,
  classifyAvailability,
  computeFundPace,
  DEFAULT_DANGER_THRESHOLDS,
  resolveDangerThresholds,
  watchLineCents,
  worstDangerState,
} from "./danger";
export {
  assertIntegerCents,
  assertPositiveCents,
  calendarMonth,
  normalizeDate,
  previousCalendarMonth,
} from "./invariants";
export {
  buildAnnualSummary,
  buildPlannedVsActual,
  computeMonthCashflow,
  DEFAULT_AS_PLANNED_BAND_PERCENT,
  DEFAULT_MAJOR_POP_UP_CENTS,
  drawRowsFor,
  lastDayOfMonth,
  monthLabelOf,
} from "./pva";
export type {
  Account,
  AccountKind,
  Allocation,
  AnnualMonthRow,
  AnnualSummary,
  AnnualSummaryOptions,
  BudgetEngine,
  BudgetEngineRuntime,
  BudgetMonth,
  Category,
  CategoryAvailable,
  CategoryGroup,
  DangerCategoryState,
  DangerState,
  DangerZoneOptions,
  DangerZoneReport,
  DangerZoneThresholdOverrides,
  DangerZoneThresholds,
  EngineState,
  Fund,
  FundDangerState,
  FundDraw,
  FundKind,
  FundPace,
  LifeEventKind,
  MajorPopUpRow,
  MonthCashflow,
  PlannedVsActualReport,
  PvaCategoryRow,
  PvaDrawRow,
  PvaOptions,
  PvaVerdict,
  ConfirmedLifeEvent,
  NetWorthPoint,
  ReviewState,
  RiskAppetite,
  Transaction,
  TransactionInput,
  Transfer,
  TransferInput,
  TxKind,
} from "./types";
